/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppScrapeRouteImport } from './routes/_app/scrape'
import { Route as AppTestsRouteImport } from './routes/_app/tests'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppProfilesNameRouteImport } from './routes/_app/profiles/$name'
import { Route as AppProfilesNewRouteImport } from './routes/_app/profiles/new'
import { Route as AppScrapeIdRouteImport } from './routes/_app/scrape_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppScrapeRoute = AppScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesNameRoute = AppProfilesNameRouteImport.update({
  id: '/profiles/$name',
  path: '/profiles/$name',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesNewRoute = AppProfilesNewRouteImport.update({
  id: '/profiles/new',
  path: '/profiles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppScrapeIdRoute = AppScrapeIdRouteImport.update({
  id: '/scrape_/$id',
  path: '/scrape/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/results': typeof AppResultsRoute
  '/scrape': typeof AppScrapeRoute
  '/tests': typeof AppTestsRoute
  '/profiles/$name': typeof AppProfilesNameRoute
  '/profiles/new': typeof AppProfilesNewRoute
  '/scrape/$id': typeof AppScrapeIdRoute
  '/profiles/': typeof AppProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/results': typeof AppResultsRoute
  '/scrape': typeof AppScrapeRoute
  '/tests': typeof AppTestsRoute
  '/': typeof AppIndexRoute
  '/profiles/$name': typeof AppProfilesNameRoute
  '/profiles/new': typeof AppProfilesNewRoute
  '/scrape/$id': typeof AppScrapeIdRoute
  '/profiles': typeof AppProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/scrape': typeof AppScrapeRoute
  '/_app/tests': typeof AppTestsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/profiles/$name': typeof AppProfilesNameRoute
  '/_app/profiles/new': typeof AppProfilesNewRoute
  '/_app/scrape_/$id': typeof AppScrapeIdRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/results'
    | '/scrape'
    | '/tests'
    | '/profiles/$name'
    | '/profiles/new'
    | '/scrape/$id'
    | '/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/results'
    | '/scrape'
    | '/tests'
    | '/'
    | '/profiles/$name'
    | '/profiles/new'
    | '/scrape/$id'
    | '/profiles'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/history'
    | '/_app/results'
    | '/_app/scrape'
    | '/_app/tests'
    | '/_app/'
    | '/_app/profiles/$name'
    | '/_app/profiles/new'
    | '/_app/scrape_/$id'
    | '/_app/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scrape': {
      id: '/_app/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof AppScrapeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$name': {
      id: '/_app/profiles/$name'
      path: '/profiles/$name'
      fullPath: '/profiles/$name'
      preLoaderRoute: typeof AppProfilesNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/new': {
      id: '/_app/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof AppProfilesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scrape_/$id': {
      id: '/_app/scrape_/$id'
      path: '/scrape/$id'
      fullPath: '/scrape/$id'
      preLoaderRoute: typeof AppScrapeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppResultsRoute: typeof AppResultsRoute
  AppScrapeRoute: typeof AppScrapeRoute
  AppTestsRoute: typeof AppTestsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfilesNameRoute: typeof AppProfilesNameRoute
  AppProfilesNewRoute: typeof AppProfilesNewRoute
  AppScrapeIdRoute: typeof AppScrapeIdRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppResultsRoute: AppResultsRoute,
  AppScrapeRoute: AppScrapeRoute,
  AppTestsRoute: AppTestsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfilesNameRoute: AppProfilesNameRoute,
  AppProfilesNewRoute: AppProfilesNewRoute,
  AppScrapeIdRoute: AppScrapeIdRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
